// <auto-generated />
namespace NGKS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tablemodification12142016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tablemodification12142016));
        
        string IMigrationMetadata.Id
        {
            get { return "201612141046152_Table-modification-12-14-2016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
